### ISSUE TITLE
Plugin displays <?> "Character not found" character in Avogadro2 menu entries in Windows 10

### ISSUE THREAD

**Issue by Ineluki80** [matterhorn103/avo_xtb#2]
Source: The menu entries "Configure ..." and "Get xtb ..." use the single unicode character "…" 
Problem: Menues in Windows 10 show this character as "�"
Solution: Replace "…" with "..." three consecutive dots in config.py : 201 and install.py : 155

**Comment by matterhorn103** [comment]
This is done to match the other menu items in Avogadro, which have been standardized to use the ellipsis character rather than three full stops/periods. So I'll be keeping it as is.

Obviously the fact that it is displayed incorrectly is a problem that needs fixing, though.

I assume that other menu options with … display correctly for you?

In which case there is some problem in the way that Avogadro gets the options json from plugins. Presumably down to the character encoding used at various stages.

**Comment by Ineluki80** [comment]
Indeed, Avogadro's native menu items show correctly.
But I was able to fix the problem: Inserting the following code in config.py line 41 should do the trick.
'''sys.stdout.reconfigure(encoding='utf-8')'''

**Comment by matterhorn103** [comment]
Thanks for digging on this. Seems like it should be an easy fix.

It would be better to fix this on Avogadro's side of things though, as all plugins are going to be behaving the same on Windows.

**Comment by Ineluki80** [comment]
Are you going to open the forum thread or shall I do it ?

**Comment by matterhorn103** [comment]
I opened an issue but you're welcome to start the forum thread!

**Comment by matterhorn103** [comment]
True. I added the fix for now.

@Ineluki80 I would appreciate you testing the plugin again. Then I'll make a 0.2.1 release.

**Comment by Ineluki80** [comment]
Works beautifully now.
